// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeMao_SpeechRecognise.proto

package com.ubtechinc.codemao;

public final class CodeMaoSpeechRecognise {
  private CodeMaoSpeechRecognise() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SpeechRecogniseRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpeechRecogniseRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 timeLimit = 1;</code>
     */
    int getTimeLimit();

    /**
     * <code>string asrText = 2;</code>
     */
    java.lang.String getAsrText();
    /**
     * <code>string asrText = 2;</code>
     */
    com.google.protobuf.ByteString
        getAsrTextBytes();
  }
  /**
   * Protobuf type {@code SpeechRecogniseRequest}
   */
  public  static final class SpeechRecogniseRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpeechRecogniseRequest)
      SpeechRecogniseRequestOrBuilder {
    // Use SpeechRecogniseRequest.newBuilder() to construct.
    private SpeechRecogniseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeechRecogniseRequest() {
      timeLimit_ = 0;
      asrText_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SpeechRecogniseRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timeLimit_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              asrText_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.class, com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.Builder.class);
    }

    public static final int TIMELIMIT_FIELD_NUMBER = 1;
    private int timeLimit_;
    /**
     * <code>int32 timeLimit = 1;</code>
     */
    public int getTimeLimit() {
      return timeLimit_;
    }

    public static final int ASRTEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object asrText_;
    /**
     * <code>string asrText = 2;</code>
     */
    public java.lang.String getAsrText() {
      java.lang.Object ref = asrText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asrText_ = s;
        return s;
      }
    }
    /**
     * <code>string asrText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAsrTextBytes() {
      java.lang.Object ref = asrText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asrText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timeLimit_ != 0) {
        output.writeInt32(1, timeLimit_);
      }
      if (!getAsrTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, asrText_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timeLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timeLimit_);
      }
      if (!getAsrTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, asrText_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest)) {
        return super.equals(obj);
      }
      com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest other = (com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest) obj;

      boolean result = true;
      result = result && (getTimeLimit()
          == other.getTimeLimit());
      result = result && getAsrText()
          .equals(other.getAsrText());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMELIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getTimeLimit();
      hash = (37 * hash) + ASRTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getAsrText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpeechRecogniseRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpeechRecogniseRequest)
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.class, com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.Builder.class);
      }

      // Construct using com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timeLimit_ = 0;

        asrText_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseRequest_descriptor;
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest getDefaultInstanceForType() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.getDefaultInstance();
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest build() {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest buildPartial() {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest result = new com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest(this);
        result.timeLimit_ = timeLimit_;
        result.asrText_ = asrText_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest) {
          return mergeFrom((com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest other) {
        if (other == com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest.getDefaultInstance()) return this;
        if (other.getTimeLimit() != 0) {
          setTimeLimit(other.getTimeLimit());
        }
        if (!other.getAsrText().isEmpty()) {
          asrText_ = other.asrText_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int timeLimit_ ;
      /**
       * <code>int32 timeLimit = 1;</code>
       */
      public int getTimeLimit() {
        return timeLimit_;
      }
      /**
       * <code>int32 timeLimit = 1;</code>
       */
      public Builder setTimeLimit(int value) {
        
        timeLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 timeLimit = 1;</code>
       */
      public Builder clearTimeLimit() {
        
        timeLimit_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object asrText_ = "";
      /**
       * <code>string asrText = 2;</code>
       */
      public java.lang.String getAsrText() {
        java.lang.Object ref = asrText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asrText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asrText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAsrTextBytes() {
        java.lang.Object ref = asrText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asrText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asrText = 2;</code>
       */
      public Builder setAsrText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asrText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string asrText = 2;</code>
       */
      public Builder clearAsrText() {
        
        asrText_ = getDefaultInstance().getAsrText();
        onChanged();
        return this;
      }
      /**
       * <code>string asrText = 2;</code>
       */
      public Builder setAsrTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        asrText_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SpeechRecogniseRequest)
    }

    // @@protoc_insertion_point(class_scope:SpeechRecogniseRequest)
    private static final com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest();
    }

    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeechRecogniseRequest>
        PARSER = new com.google.protobuf.AbstractParser<SpeechRecogniseRequest>() {
      public SpeechRecogniseRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SpeechRecogniseRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpeechRecogniseRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeechRecogniseRequest> getParserForType() {
      return PARSER;
    }

    public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SpeechRecogniseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SpeechRecogniseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool isSuccess = 1;</code>
     */
    boolean getIsSuccess();

    /**
     * <code>int32 resultCode = 2;</code>
     */
    int getResultCode();

    /**
     * <code>string text = 3;</code>
     */
    java.lang.String getText();
    /**
     * <code>string text = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();
  }
  /**
   * Protobuf type {@code SpeechRecogniseResponse}
   */
  public  static final class SpeechRecogniseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SpeechRecogniseResponse)
      SpeechRecogniseResponseOrBuilder {
    // Use SpeechRecogniseResponse.newBuilder() to construct.
    private SpeechRecogniseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SpeechRecogniseResponse() {
      isSuccess_ = false;
      resultCode_ = 0;
      text_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SpeechRecogniseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              isSuccess_ = input.readBool();
              break;
            }
            case 16: {

              resultCode_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              text_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.class, com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.Builder.class);
    }

    public static final int ISSUCCESS_FIELD_NUMBER = 1;
    private boolean isSuccess_;
    /**
     * <code>bool isSuccess = 1;</code>
     */
    public boolean getIsSuccess() {
      return isSuccess_;
    }

    public static final int RESULTCODE_FIELD_NUMBER = 2;
    private int resultCode_;
    /**
     * <code>int32 resultCode = 2;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object text_;
    /**
     * <code>string text = 3;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      }
    }
    /**
     * <code>string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isSuccess_ != false) {
        output.writeBool(1, isSuccess_);
      }
      if (resultCode_ != 0) {
        output.writeInt32(2, resultCode_);
      }
      if (!getTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, text_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isSuccess_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuccess_);
      }
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, resultCode_);
      }
      if (!getTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, text_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse)) {
        return super.equals(obj);
      }
      com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse other = (com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse) obj;

      boolean result = true;
      result = result && (getIsSuccess()
          == other.getIsSuccess());
      result = result && (getResultCode()
          == other.getResultCode());
      result = result && getText()
          .equals(other.getText());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSuccess());
      hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
      hash = (53 * hash) + getResultCode();
      hash = (37 * hash) + TEXT_FIELD_NUMBER;
      hash = (53 * hash) + getText().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SpeechRecogniseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SpeechRecogniseResponse)
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.class, com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.Builder.class);
      }

      // Construct using com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        isSuccess_ = false;

        resultCode_ = 0;

        text_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.internal_static_SpeechRecogniseResponse_descriptor;
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse getDefaultInstanceForType() {
        return com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.getDefaultInstance();
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse build() {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse buildPartial() {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse result = new com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse(this);
        result.isSuccess_ = isSuccess_;
        result.resultCode_ = resultCode_;
        result.text_ = text_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse) {
          return mergeFrom((com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse other) {
        if (other == com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse.getDefaultInstance()) return this;
        if (other.getIsSuccess() != false) {
          setIsSuccess(other.getIsSuccess());
        }
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        if (!other.getText().isEmpty()) {
          text_ = other.text_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isSuccess_ ;
      /**
       * <code>bool isSuccess = 1;</code>
       */
      public boolean getIsSuccess() {
        return isSuccess_;
      }
      /**
       * <code>bool isSuccess = 1;</code>
       */
      public Builder setIsSuccess(boolean value) {
        
        isSuccess_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isSuccess = 1;</code>
       */
      public Builder clearIsSuccess() {
        
        isSuccess_ = false;
        onChanged();
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 resultCode = 2;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object text_ = "";
      /**
       * <code>string text = 3;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string text = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder clearText() {
        
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>string text = 3;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        text_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SpeechRecogniseResponse)
    }

    // @@protoc_insertion_point(class_scope:SpeechRecogniseResponse)
    private static final com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse();
    }

    public static com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SpeechRecogniseResponse>
        PARSER = new com.google.protobuf.AbstractParser<SpeechRecogniseResponse>() {
      public SpeechRecogniseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SpeechRecogniseResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SpeechRecogniseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SpeechRecogniseResponse> getParserForType() {
      return PARSER;
    }

    public com.ubtechinc.codemao.CodeMaoSpeechRecognise.SpeechRecogniseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechRecogniseRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechRecogniseRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpeechRecogniseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpeechRecogniseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035CodeMao_SpeechRecognise.proto\"<\n\026Speec" +
      "hRecogniseRequest\022\021\n\ttimeLimit\030\001 \001(\005\022\017\n\007" +
      "asrText\030\002 \001(\t\"N\n\027SpeechRecogniseResponse" +
      "\022\021\n\tisSuccess\030\001 \001(\010\022\022\n\nresultCode\030\002 \001(\005\022" +
      "\014\n\004text\030\003 \001(\tB\027\n\025com.ubtechinc.codemaob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SpeechRecogniseRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SpeechRecogniseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechRecogniseRequest_descriptor,
        new java.lang.String[] { "TimeLimit", "AsrText", });
    internal_static_SpeechRecogniseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SpeechRecogniseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpeechRecogniseResponse_descriptor,
        new java.lang.String[] { "IsSuccess", "ResultCode", "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
