// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeMao_StopSpeechRecognise.proto

package com.ubtechinc.codemao;

public final class CodeMaoStopSpeechRecognise {
    private CodeMaoStopSpeechRecognise() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    public interface StopSpeechRecogniseRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:StopSpeechRecogniseRequest)
            com.google.protobuf.MessageOrBuilder {
    }
    /**
     * Protobuf type {@code StopSpeechRecogniseRequest}
     */
    public  static final class StopSpeechRecogniseRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:StopSpeechRecogniseRequest)
            StopSpeechRecogniseRequestOrBuilder {
        // Use StopSpeechRecogniseRequest.newBuilder() to construct.
        private StopSpeechRecogniseRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private StopSpeechRecogniseRequest() {
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private StopSpeechRecogniseRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.class, com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.Builder.class);
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest)) {
                return super.equals(obj);
            }
            com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest other = (com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest) obj;

            boolean result = true;
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code StopSpeechRecogniseRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:StopSpeechRecogniseRequest)
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.class, com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.Builder.class);
            }

            // Construct using com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseRequest_descriptor;
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest getDefaultInstanceForType() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.getDefaultInstance();
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest build() {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest buildPartial() {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest result = new com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest(this);
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest) {
                    return mergeFrom((com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest other) {
                if (other == com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest.getDefaultInstance()) return this;
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:StopSpeechRecogniseRequest)
        }

        // @@protoc_insertion_point(class_scope:StopSpeechRecogniseRequest)
        private static final com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest();
        }

        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<StopSpeechRecogniseRequest>
                PARSER = new com.google.protobuf.AbstractParser<StopSpeechRecogniseRequest>() {
            public StopSpeechRecogniseRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new StopSpeechRecogniseRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<StopSpeechRecogniseRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<StopSpeechRecogniseRequest> getParserForType() {
            return PARSER;
        }

        public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    public interface StopSpeechRecogniseResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:StopSpeechRecogniseResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool isSuccess = 1;</code>
         */
        boolean getIsSuccess();

        /**
         * <code>int32 resultCode = 2;</code>
         */
        int getResultCode();
    }
    /**
     * Protobuf type {@code StopSpeechRecogniseResponse}
     */
    public  static final class StopSpeechRecogniseResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:StopSpeechRecogniseResponse)
            StopSpeechRecogniseResponseOrBuilder {
        // Use StopSpeechRecogniseResponse.newBuilder() to construct.
        private StopSpeechRecogniseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private StopSpeechRecogniseResponse() {
            isSuccess_ = false;
            resultCode_ = 0;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private StopSpeechRecogniseResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            isSuccess_ = input.readBool();
                            break;
                        }
                        case 16: {

                            resultCode_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.class, com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.Builder.class);
        }

        public static final int ISSUCCESS_FIELD_NUMBER = 1;
        private boolean isSuccess_;
        /**
         * <code>bool isSuccess = 1;</code>
         */
        public boolean getIsSuccess() {
            return isSuccess_;
        }

        public static final int RESULTCODE_FIELD_NUMBER = 2;
        private int resultCode_;
        /**
         * <code>int32 resultCode = 2;</code>
         */
        public int getResultCode() {
            return resultCode_;
        }

        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (isSuccess_ != false) {
                output.writeBool(1, isSuccess_);
            }
            if (resultCode_ != 0) {
                output.writeInt32(2, resultCode_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (isSuccess_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, isSuccess_);
            }
            if (resultCode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, resultCode_);
            }
            memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse)) {
                return super.equals(obj);
            }
            com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse other = (com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse) obj;

            boolean result = true;
            result = result && (getIsSuccess()
                    == other.getIsSuccess());
            result = result && (getResultCode()
                    == other.getResultCode());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ISSUCCESS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getIsSuccess());
            hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
            hash = (53 * hash) + getResultCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }
        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }
        public static Builder newBuilder(com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        /**
         * Protobuf type {@code StopSpeechRecogniseResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:StopSpeechRecogniseResponse)
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponseOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseResponse_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.class, com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.Builder.class);
            }

            // Construct using com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }
            public Builder clear() {
                super.clear();
                isSuccess_ = false;

                resultCode_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.internal_static_StopSpeechRecogniseResponse_descriptor;
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse getDefaultInstanceForType() {
                return com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.getDefaultInstance();
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse build() {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse buildPartial() {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse result = new com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse(this);
                result.isSuccess_ = isSuccess_;
                result.resultCode_ = resultCode_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse) {
                    return mergeFrom((com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse other) {
                if (other == com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse.getDefaultInstance()) return this;
                if (other.getIsSuccess() != false) {
                    setIsSuccess(other.getIsSuccess());
                }
                if (other.getResultCode() != 0) {
                    setResultCode(other.getResultCode());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private boolean isSuccess_ ;
            /**
             * <code>bool isSuccess = 1;</code>
             */
            public boolean getIsSuccess() {
                return isSuccess_;
            }
            /**
             * <code>bool isSuccess = 1;</code>
             */
            public Builder setIsSuccess(boolean value) {

                isSuccess_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>bool isSuccess = 1;</code>
             */
            public Builder clearIsSuccess() {

                isSuccess_ = false;
                onChanged();
                return this;
            }

            private int resultCode_ ;
            /**
             * <code>int32 resultCode = 2;</code>
             */
            public int getResultCode() {
                return resultCode_;
            }
            /**
             * <code>int32 resultCode = 2;</code>
             */
            public Builder setResultCode(int value) {

                resultCode_ = value;
                onChanged();
                return this;
            }
            /**
             * <code>int32 resultCode = 2;</code>
             */
            public Builder clearResultCode() {

                resultCode_ = 0;
                onChanged();
                return this;
            }
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:StopSpeechRecogniseResponse)
        }

        // @@protoc_insertion_point(class_scope:StopSpeechRecogniseResponse)
        private static final com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse();
        }

        public static com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<StopSpeechRecogniseResponse>
                PARSER = new com.google.protobuf.AbstractParser<StopSpeechRecogniseResponse>() {
            public StopSpeechRecogniseResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new StopSpeechRecogniseResponse(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<StopSpeechRecogniseResponse> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<StopSpeechRecogniseResponse> getParserForType() {
            return PARSER;
        }

        public com.ubtechinc.codemao.CodeMaoStopSpeechRecognise.StopSpeechRecogniseResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_StopSpeechRecogniseRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_StopSpeechRecogniseRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_StopSpeechRecogniseResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_StopSpeechRecogniseResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n!CodeMao_StopSpeechRecognise.proto\"\034\n\032S" +
                        "topSpeechRecogniseRequest\"D\n\033StopSpeechR" +
                        "ecogniseResponse\022\021\n\tisSuccess\030\001 \001(\010\022\022\n\nr" +
                        "esultCode\030\002 \001(\005B\027\n\025com.ubtechinc.codemao" +
                        "b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_StopSpeechRecogniseRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_StopSpeechRecogniseRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_StopSpeechRecogniseRequest_descriptor,
                new java.lang.String[] { });
        internal_static_StopSpeechRecogniseResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_StopSpeechRecogniseResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_StopSpeechRecogniseResponse_descriptor,
                new java.lang.String[] { "IsSuccess", "ResultCode", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
